# ----------------------------------------------------------
# DataSource settings
#     set here configurations for the database connection
# ----------------------------------------------------------
spring:
 datasource:
  url: jdbc:mysql://localhost:33301/o3s
  username: o3s
  password: osiris
  driverClassName: com.mysql.jdbc.Driver
  platform: mysql
  initialize: true
 jpa:
  show-sql: true
  
hibernate:
 dialect: org.hibernate.dialect.MySQL5Dialect
 
# ----------------------------------------------------------
# Flyway settings for database update
#   should be able to re-use spring datasource configuration
# ----------------------------------------------------------    
flyway:
 locations: classpath:/database
 enabled: true
  
# ----------------------------------------------------------
# Embedded Server settings
# ----------------------------------------------------------  
server:
 port: 9091
 contextPath: 
 
logging:
 level:
  org:
   springframework: INFO
   hibernate: INFO
